config {
    type: "incremental", 
    //if type incremental is withouth uniquekey then it will simply insert the data, if we have a uniquekey defined, then it will act as merge -- add new data and updaed old data on key.
    // schema: "sales_poc_dev",
    name: "t_sales_stats",
    tags: ["final_fact",'fact_gen'],
    description: ""
}


SELECT
  CURRENT_DATETIME() AS LOAD_TIME,
  BPARTNER,
  BUS_AREA,
  CACONT_ACC,
  COMP_CODE,
  COSTCENTER,
  COUNTRY,
  CURRENCY,
  DATEFROM,
  DATETO,
  DIVISION,
  PSTNG_DATE,
  REGION,
  CAST(UCCNTRCNT AS DECIMAL) as UCCNTRCNT ,
  CAST(UCCONT_CNT AS DECIMAL) as UCCONT_CNT,
  UCMOVEIN_D,
  UCMOVEOUTD,
  UCPORTION,
  UNIT,
  CAST(VAR_VR AS DECIMAL) as VAR_VR,
  ZUCBILDOC,
  ZUCCUSSEG,
  ZUCDOCINV,
  ZUCRECKEY,
  UC_DATEFRO,
  UC_DATETO,
  CALMONTH,
  NULL AS ZZ_FRACTION,
  ZUCCALEG2,
  CAST(ZGASQTY AS DECIMAL) as ZGASQTY,
  CAST(ZGASLQTY AS DECIMAL) as ZGASLQTY,
  ZGAS_UOM,
  ZGASL_UOM,
  CAST(ZGASAMT AS DECIMAL) as ZGASAMT,
  CAST(ZEDMQTY AS DECIMAL) as ZEDMQTY,
  CAST(ZEDMAMT AS DECIMAL) as ZEDMAMT
FROM
  ${ref("v_sales_stats")}