steps:
  - name: 'node:18'
    id: 'Install Dependencies'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g @dataform/cli
        npm install
        export PATH="$(npm bin -g):$PATH"
        dataform --version

  - name: 'node:18'
    id: 'Compile'
    entrypoint: bash
    args:
      - -c
      - |
        export PATH="$(npm bin -g):$PATH"
        dataform compile --vars='{"env":"dev"}'

  - name: 'node:18'
    id: 'Run Tests'
    entrypoint: bash
    args:
      - -c
      - |
        export PATH="$(npm bin -g):$PATH"
        dataform test --vars='{"env":"dev"}'

options:
  logging: CLOUD_LOGGING_ONLY