steps:
  - name: 'node:18'
    id: 'Install Dependencies'
    entrypoint: bash
    args:
      - -c
      - |
        npm install @dataform/cli@latest

  - name: 'node:18'
    id: 'Compile'
    entrypoint: bash
    args:
      - -c
      - |
        npx @dataform/cli compile --vars='{"env":"dev"}'

  - name: 'node:18'
    id: 'Run Tests'
    entrypoint: bash
    args:
      - -c
      - |
        npx @dataform/cli test --project-id=$_PROJECT_ID --location=$_REGION --repository-id=$_DATAFORM_REPO --vars='{"env":"dev"}'

options:
  logging: CLOUD_LOGGING_ONLY