config {
  type: "incremental",
  schema: "sales_cdc_poc",
  name: "ZSEC_PURA",
  uniqueKey: ["COMP_CODE", "DOC_TYPE", "SALESEMPLY"],
  tags: ["bw_migration"]
}

-- MERGE load: key fields are COMP_CODE, DOC_TYPE, SALESEMPLY

WITH
  src_ZTSOBJ_C AS (
    SELECT
      NULL                        AS `0FISCVARNT`,
      COMP_CODE,
      DOC_TYPE,
      SALESEMPLY,
      AMNT,
      IMODOCCATR,
      STAT_CURR,
      S4SOLD_TO,
      CPR_CREATE,
      CUST_GRP1,
      CRMSALORGX,
      PR_CAT_SAL,
      LOC_CURRCY,
      NULL                        AS `0FISCYEAR`,
      AB_ITEM
    FROM
      ${ref("sales_cdc_poc","ZTSOBJ_C")}
  )

SELECT
  `0FISCVARNT`,
  COALESCE(COMP_CODE,    '')  AS COMP_CODE,
  COALESCE(DOC_TYPE,     '')  AS DOC_TYPE,
  COALESCE(SALESEMPLY,   '')  AS SALESEMPLY,
  AMNT,
  IMODOCCATR,
  STAT_CURR,
  S4SOLD_TO,
  CPR_CREATE,
  CUST_GRP1,
  CRMSALORGX,
  PR_CAT_SAL,
  LOC_CURRCY,
  `0FISCYEAR`,
  AB_ITEM
FROM
  src_ZTSOBJ_C
${when(incremental(), `WHERE CPR_CREATE > (
    SELECT MAX(CPR_CREATE) FROM ${self()}
)`)}