config {
  type: "incremental",
  schema: "sales_cdc_poc",
  name: "ZSEC_SALA",
  uniqueKey: ["COMP_CODE", "DOC_TYPE", "SALESEMPLY"],
  tags: ["bw_migration"]
}

-- MERGE load: key fields are COMP_CODE, DOC_TYPE, SALESEMPLY

WITH
  src_ZTSOBJ_C AS (
    SELECT
      COMP_CODE,
      DOC_TYPE,
      SALESEMPLY,
      --AMNT,
      STAT_CURR,
      IMODOCCATR,
      S4SOLD_TO,
      CPR_CREATE,
      LOC_CURRCY,
      CUST_GRP1,
      CRMSALORGX,
      PR_CAT_SAL,
      AB_ITEM,
      FISCVARNT, ----- updated to remvoe the 0
      FISCYEAR
    FROM ${ref("ZTSOBJ_C")}
  )

SELECT
  COALESCE(COMP_CODE,  '')  AS COMP_CODE,
  COALESCE(DOC_TYPE,   '')  AS DOC_TYPE,
  COALESCE(SALESEMPLY, '')  AS SALESEMPLY,
  --AMNT,
  STAT_CURR,
  IMODOCCATR,
  S4SOLD_TO,
  CPR_CREATE,
  LOC_CURRCY,
  CUST_GRP1,
  CRMSALORGX,
  PR_CAT_SAL,
  AB_ITEM,
  FISCVARNT,  ----- updated to remvoe the 0
  FISCYEAR
FROM src_ZTSOBJ_C
${when(incremental(), `WHERE CPR_CREATE > (
    SELECT MAX(CPR_CREATE) FROM ${self()}
)`)}