config {
  type: "incremental",
  schema: "sales_cdc_poc",
  name: "ZTSOBJ",
  uniqueKey: ["COMP_CODE", "DOC_TYPE", "SALESEMPLY"],
  tags: ["bw_migration"]
}

-- MERGE load: key fields are COMP_CODE, DOC_TYPE, SALESEMPLY

WITH
  src_ZDS_HDR1 AS (
    SELECT
      COMP_CODE,
      DOC_TYPE,
      SALESEMPLY,
      IMODOCCATR,
      S4SOLD_TO,
      STAT_CURR,
      CPR_CREATE,
      CUST_GRP1,
      AB_ITEM,
      CRMSALORGX,
      PR_CAT_SAL,
      LOC_CURRCY,
      `0FISCVARNT`,
      `0FISCYEAR`
    FROM ${ref("ZDS_HDR1")}
    ${when(incremental(), `WHERE CPR_CREATE > (
      SELECT MAX(CPR_CREATE) FROM ${self()}
    )`)}
  )

SELECT
  COMP_CODE        AS COMP_CODE,
  DOC_TYPE         AS DOC_TYPE,
  SALESEMPLY       AS SALESEMPLY,
  IMODOCCATR       AS IMODOCCATR,
  S4SOLD_TO        AS S4SOLD_TO,
  STAT_CURR        AS STAT_CURR,
  CPR_CREATE       AS CPR_CREATE,
  CUST_GRP1        AS CUST_GRP1,
  AB_ITEM          AS AB_ITEM,
  CRMSALORGX       AS CRMSALORGX,
  PR_CAT_SAL       AS PR_CAT_SAL,
  LOC_CURRCY       AS LOC_CURRCY,
  `0FISCVARNT`     AS `0FISCVARNT`,
  `0FISCYEAR`      AS `0FISCYEAR`
FROM src_ZDS_HDR1