config {
    type: "table",
    name: "fact_sales_gas_alloc_poc",
    tags: ["final_fact",'fact_gen'],
    description: "",
    schema: dataform.projectConfig.vars.env === "prod" ?
        "sales_poc_prod" :
        dataform.projectConfig.vars.env === "staging" ?
        "sales_poc_stg" :
        "sales_poc_dev"
}


SELECT
  BPARTNER,
  BUS_AREA,
  CACONT_ACC,
  COMP_CODE,
  COSTCENTER,
  COUNTRY,
  CURRENCY,
  DATEFROM,
  DATETO,
  DIVISION,
  PSTNG_DATE,
  REGION,
  CAST(UCCNTRCNT AS DECIMAL) as UCCNTRCNT ,
  CAST(UCCONT_CNT AS DECIMAL) as UCCONT_CNT,
  UCMOVEIN_D,
  UCMOVEOUTD,
  UCPORTION,
  UNIT,
  CAST(VAR_VR AS DECIMAL) as VAR_VR,
  ZUCBILDOC,
  ZUCCUSSEG,
  ZUCDOCINV,
  ZUCRECKEY,
  UC_DATEFRO,
  UC_DATETO,
  CALMONTH,
  NULL AS ZZ_FRACTION,
  ZUCCALEG2,
  CAST(ZGASQTY AS DECIMAL) as ZGASQTY,
  CAST(ZGASLQTY AS DECIMAL) as ZGASLQTY,
  ZGAS_UOM,
  ZGASL_UOM,
  CAST(ZGASAMT AS DECIMAL) as ZGASAMT,
  CAST(ZEDMQTY AS DECIMAL) as ZEDMQTY,
  CAST(ZEDMAMT AS DECIMAL) as ZEDMAMT
FROM
  ${ref("uc_sales_stats_prepared")}
