config {
    type: "view",
    //schema: "sales_curated_poc",
    name: "src_sales_cdc",
    tags: ["sales_gas_alloc"],
    description: "",
    schema: dataform.projectConfig.vars.env === "prod" ?
        "sales_poc_prod" : dataform.projectConfig.vars.env === "staging" ?
        "sales_poc_stg" : "sales_poc_dev"
}

SELECT
  *,
  CURRENT_TIMESTAMP() AS CURRENT_TIMESTAMP,
FROM
  ${ref("BIW_ISU_ESTA")}
